#
# Copyright (c) 2013-2014 by Lifted Studios. All Rights Reserved.
#

LineLength:
  Enabled: true
  Max: 100

SignalException:
  Enabled: true
  EnforcedStyle: only_raise

SingleLineBlockParams:
  Enabled: false
